server:
    port: 0
spring:
    application:
         name: associate-service
    datasource:
       url: jdbc:mysql://localhost:3306/hr
       username: root
       password: jayanti@2021
    jpa:
       hibernate:
          ddl-auto: create
    boot:
       client:
          admin:
             url: http://localhost:8888
eureka:
 instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
 client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
   management:
      endpoints:
   web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: department-service.log  
           
         